# version: '3.8'

# Dev mode only!!!

services:

  finance-api:
    container_name: finance-api
    hostname: finance-api
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
      # dockerfile: ./Dockerfile
      args:
        - FINANCE_PORT=9098
    command: uvicorn server:app --host 0.0.0.0 --port 9098 --reload
    image: omarzos/finance-api
    ports:
      - 9098:9098
    environment:
      - FINANCE_PORT=9098
      - SQL_SCHEMA=${SQL_SCHEMA}
      - SQL_HOST=${SQL_HOST}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_PORT=${SQL_PORT}
    networks:
      - gluttex-net
    volumes:
      - ./:/code
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


volumes:
  volumes:
    driver: local


networks:
  gluttex-net:
    external: true
#     name: gluttex-net
#     driver: bridge